title: Benjamin AIMARD
description: Consultant en Cybersécurité, Réseau et Développement
linkedin: https://www.linkedin.com/in/benjaminaimard/
rootme: https://www.root-me.org/Juxo
yesWeHack: https://www.YesWeHack.com
twitter: https://twitter.com/N00BjuX0
theme: jekyll-theme-hacker