title: Benjamin AIMARD - En cours de construction
description: Consultant en Cybersécurité, Réseau et Développement depuis 2016
linkedin: https://www.linkedin.com/in/benjaminaimard/
rootme: https://www.root-me.org/Juxo
yesWeHack: https://www.YesWeHack.com
twitter: https://twitter.com/N00BjuX0
theme: jekyll-theme-hacker
github: https://github.com/baimard
